// Project SOT (served, frozen). Easy tier — Firework Simulator. All 8 chapters.
// Code fields use template literals so they stay verbatim (no escaping).
window.BUILDIT_SOT = {
  project: "firework-tkinter",
  title: "Firework Simulator",
  pitch: "Build a night sky you click to fill with fireworks — they streak up, burst into color, and drift down.",
  tier: "easy",
  language: "Python",
  chapters: [
    {
      id: 1, title: "The night sky",
      build: "a window that opens and fills with deep-blue night — the stage every firework happens on.",
      beat: "A dark window opens and stays.",
      steps: [
        { title: "Load the toolkit", adding: "the line that gives you Python's window-and-drawing tools.",
          code: `import tkinter as tk`,
          does: "tkinter is the toolkit built into Python for making windows and drawings. import brings it in; as tk gives it a short nickname.",
          why: "Every visible thing you build comes from this toolkit — and it ships inside Python, so there's nothing to install.",
          see: "Run python3 main.py — nothing. No window, no error, just your prompt again. That's exactly right; we only opened the toolbox.",
          checkpoint: "It ran and gave you back your prompt with no red text.",
          recovery: ["No module named tkinter — rare; paste it to the helper, it's a setup issue, not your code.", "Any other error — check the spelling: import tkinter as tk."] },
        { title: "Make a window", adding: "the window itself.",
          code: `window = tk.Tk()`,
          does: "tk.Tk() creates the main application window and hands it back. We store it in a box named window so we can talk to it later.",
          why: "This is the container everything else lives inside — the frame around your whole night sky.",
          see: "The window will blink open and instantly vanish (or you may see nothing). That's expected — you just met the most common surprise in beginner programming. The next step cures it.",
          checkpoint: "It ran with no red error. (The blink-and-vanish is not a failure here — it's the lesson.)",
          recovery: ["Red error — check the capitals: tk.Tk(), lowercase tk, capital T, lowercase k."] },
        { title: "Tell the window to stay", adding: "one line that keeps your window on screen (add it as the very last line).",
          code: `window.mainloop()`,
          does: "mainloop() starts Tkinter's event loop — an engine that keeps running, watching for clicks, keys, and the close button. Without it, the program ends and the window vanishes with it.",
          why: "Every Tkinter app ends with this line — it's the heartbeat. It's the same loop that will later let you click to launch a firework.",
          see: "A small empty gray window opens and stays open until you close it. (Last step it vanished — this is the cure.)",
          checkpoint: "The window opened and stayed.",
          recovery: ["Still vanishes — mainloop() must be the very last line, not indented inside anything.", "Red error mentioning mainloop — check the spelling: one word, lowercase."] },
        { title: "Name it and lock the size", adding: "a title, and a fixed size (add after window = tk.Tk(), before mainloop).",
          code: `window.title("Firework Simulator")\nwindow.resizable(False, False)`,
          does: "title(...) sets the title-bar text. resizable(False, False) stops the window being dragged bigger or smaller — the two Falses are width and height.",
          why: "Our night sky is a fixed-size stage. Locking it keeps the layout predictable so fireworks land where we expect.",
          see: "The title bar now reads Firework Simulator, and dragging the edge won't resize it.",
          checkpoint: "The title shows, and the edges won't resize.",
          recovery: ["Title unchanged — these lines must be after window = tk.Tk() and before window.mainloop().", "Red error — in Python, False is capitalized."] },
        { title: "Hang the night sky", adding: "the dark canvas — your stage (add just above mainloop).",
          code: `canvas = tk.Canvas(window, width=1200, height=800, bg="#0a0a1e", highlightthickness=0)\ncanvas.pack()`,
          does: "A Canvas is a blank surface you can draw on. We make it 1200x800, fill it deep midnight-blue, and remove its default border with highlightthickness=0. pack() places it in the window.",
          why: "This canvas is the stage for the entire project. Every star, the moon, every rocket and spark gets drawn here.",
          see: "A large window filled with deep midnight-blue — no border line, just clean dark sky.",
          checkpoint: "A big dark-navy window (about 1200x800), no line around the dark area. That's Beat 1 — the night sky.",
          recovery: ["Window tiny and gray — you're missing canvas.pack().", "Thin white line around the edge — check highlightthickness=0.", "Color error — it must be the text \"#0a0a1e\" in quotes."] }
      ]
    },
    {
      id: 2, title: "The moon",
      build: "a glowing moon hanging in the top-right of your night sky.",
      beat: "A moon appears with a soft glow and two craters.",
      steps: [
        { title: "The moon's glow", adding: "a soft halo where the moon will sit (add after canvas.pack(), above mainloop).",
          code: `canvas.create_oval(1040, 20, 1160, 140, fill="#3a3a5a", outline="")`,
          does: "create_oval draws an oval. The four numbers are the corners of an invisible box — top-left and bottom-right — and Tkinter draws the biggest oval that fits. fill is its color; outline=\"\" removes the black edge.",
          why: "This is your first drawing — and everything visual in this project is a shape drawn exactly like this. The four corner numbers are how you place anything.",
          see: "A soft, dim halo — a gentle lighter patch of blue-gray — in the top-right. Not bright; just a glow.",
          checkpoint: "A faint round glow in the top-right corner.",
          recovery: ["Nothing appeared — the line must come after canvas.pack() and before window.mainloop().", "A black ring around it — check outline=\"\" (two quotes, nothing between)."] },
        { title: "The moon", adding: "the bright moon itself, on top of the glow.",
          code: `canvas.create_oval(1070, 50, 1130, 110, fill="#ffffdc", outline="")`,
          does: "Another oval, a smaller box centered on the same spot, filled pale moon-yellow. Because we draw it after the glow, it sits in front — whatever you draw later lands on top.",
          why: "\"Later draws on top\" — draw order, or layering — is one of the most useful things to know about the canvas. It's why the glow came first.",
          see: "A bright pale-yellow moon appears, glowing softly inside its halo.",
          checkpoint: "A bright round moon centered in the glow.",
          recovery: ["Moon hidden or glow on top — the moon line must come after the glow line.", "Off to one side — check its numbers: 1070, 50, 1130, 110."] },
        { title: "Craters", adding: "two little shadow spots, for depth.",
          code: `canvas.create_oval(1087, 70, 1097, 80, fill="#e6e6c8", outline="")\ncanvas.create_oval(1095, 83, 1113, 91, fill="#e6e6c8", outline="")`,
          does: "Two more small ovals in a slightly darker cream, drawn on top of the moon's face. Small boxes make small ovals; they read as gentle craters.",
          why: "Tiny details make something feel real instead of flat — the same instinct will make sparks shimmer later.",
          see: "Two small spots appear on the moon's face, giving it a touch of depth. Your moon is finished.",
          checkpoint: "A glowing moon with two small craters, top-right. That's Beat 3 — the moon.",
          recovery: ["The spots don't show — both lines must come after the moon line.", "Want them elsewhere — nudge the four-number boxes."] }
      ]
    },
    {
      id: 3, title: "A living sky",
      build: "a sky full of stars that gently twinkle.",
      beat: "Stars fill the sky and twinkle — your program is alive.",
      steps: [
        { title: "Bring in randomness", adding: "a toolkit for random numbers (add at the top, under import tkinter as tk).",
          code: `import random`,
          does: "random makes random numbers — we'll use it to scatter stars so no two skies look alike.",
          why: "You'll reach for random on every firework too, to throw sparks out in all directions.",
          see: "Nothing new, no error — we only loaded a toolkit.",
          checkpoint: "It ran with no red text.",
          recovery: ["An error — check the spelling: import random."] },
        { title: "Scatter a sky full of stars", adding: "a hundred stars in random spots (add after the moon lines, above mainloop).",
          code: `stars = []\nfor i in range(100):\n    x = random.randint(0, 1200)\n    y = random.randint(0, 400)\n    size = random.choice([1, 1, 1, 2])\n    star = canvas.create_oval(x, y, x + size, y + size, fill="white", outline="")\n    stars.append({"id": star, "brightness": random.uniform(0.5, 1.0), "speed": random.uniform(0.01, 0.03)})`,
          does: "stars = [] makes a list. The for loop runs 100 times, each time drawing a tiny white oval at a random spot and remembering it (with a brightness and twinkle speed we'll use soon).",
          why: "Your first list and first for loop — make 100 of something without 100 lines. Every explosion uses this exact idea.",
          see: "The upper sky fills with a scatter of tiny white stars (still, for now).",
          checkpoint: "A sky full of little white stars across the top.",
          recovery: ["No stars — the block must come after canvas.pack().", "Indentation error — the lines under for must be indented the same."] },
        { title: "Start the heartbeat", adding: "the game loop — code that runs over and over (add after the stars, above mainloop).",
          code: `def tick():\n    window.after(16, tick)\n\ntick()`,
          does: "def tick() makes a reusable block. window.after(16, tick) asks the window to run tick again in 16ms, so it repeats about 60 times a second. tick() starts it.",
          why: "This heartbeat is the most important machine here — everything that moves happens because this loop runs and changes things a little each time.",
          see: "Nothing changes — stars sit still, no error. The engine is running, it just has no job yet.",
          checkpoint: "Everything looks the same, no red error. (A running loop with no job looks identical.)",
          recovery: ["Window freezes — the inside line must be window.after(16, tick), not tick().", "tick is not defined — the tick() line must come after the def tick(): block."] },
        { title: "Make them twinkle", adding: "the loop's first job — brightening and dimming each star (add inside tick, above the window.after line).",
          code: `    for star in stars:\n        star["brightness"] += (random.random() - 0.5) * star["speed"]\n        star["brightness"] = max(0.3, min(1.0, star["brightness"]))\n        gray = int(star["brightness"] * 255)\n        canvas.itemconfig(star["id"], fill=f"#{gray:02x}{gray:02x}{gray:02x}")`,
          does: "Each frame we nudge every star's brightness up or down a touch, keep it in range, turn it into a gray shade, and repaint the star with itemconfig (which changes a shape we already drew).",
          why: "This is the pattern behind all animation here — each frame, change something a little.",
          see: "The stars twinkle — each softly brightening and dimming on its own. Your sky is alive.",
          checkpoint: "Stars gently shimmer (a soft flicker, not harsh flashing). That's Beat 2 — a living sky.",
          recovery: ["Nothing twinkles — the lines must be inside tick, above window.after.", "Stars flash wildly — the change must be multiplied by star['speed'] (a tiny number)."] }
      ]
    },
    {
      id: 4, title: "Launch a rocket",
      build: "click anywhere and a rocket streaks up from the ground, trailing white.",
      beat: "Click — a rocket streaks up trailing white.",
      steps: [
        { title: "Get ready to launch", adding: "a list for rockets and a click that adds one (add above def tick()).",
          code: `fireworks = []\n\ndef launch(event):\n    fireworks.append({"x": event.x, "y": 800, "vx": random.uniform(-1, 1), "vy": -15, "trail": []})\n\ncanvas.bind("<Button-1>", launch)`,
          does: "fireworks is a list, like stars. launch runs on click — event tells it where. It adds a rocket starting at the bottom (y=800) under your click, shooting up (vy=-15). canvas.bind connects clicks to launch.",
          why: "Your first interaction — the program now responds to you.",
          see: "Click a few times — nothing appears yet (we're recording rockets, not drawing them). No error = good.",
          checkpoint: "It runs; clicking causes no error.",
          recovery: ["Error about event — the function must be def launch(event):.", "Clicking errors — check the bind text \"<Button-1>\"."] },
        { title: "Draw the rockets", adding: "drawing each rocket every frame (add inside tick, after the star loop).",
          code: `    canvas.delete("firework")\n    for fw in fireworks:\n        canvas.create_oval(fw["x"] - 3, fw["y"] - 3, fw["x"] + 3, fw["y"] + 3, fill="white", outline="", tags="firework")`,
          does: "Each frame we erase last frame's rockets with canvas.delete(\"firework\") — only shapes tagged \"firework\", leaving stars and moon — then draw a white dot for each rocket, tagging it.",
          why: "Erase-then-redraw is how everything that moves is animated — and how the explosion's sparks get drawn soon.",
          see: "Click — a white dot appears at the bottom where you clicked. It doesn't move yet.",
          checkpoint: "Clicking puts a white dot at the bottom of the sky.",
          recovery: ["Stars disappear too — delete \"firework\", not everything.", "No dot — these lines must be inside tick."] },
        { title: "Make it fly", adding: "gravity and motion (add inside tick, above the canvas.delete line).",
          code: `    for fw in fireworks:\n        fw["vy"] += 0.3\n        fw["x"] += fw["vx"]\n        fw["y"] += fw["vy"]`,
          does: "Each frame gravity adds to downward speed (vy += 0.3), then we move the rocket. Starting at vy=-15 (up), it rises, slows, and arcs back down.",
          why: "This is physics — the very same lines that make sparks fall later.",
          see: "Click — the rocket shoots up, slows as it climbs, and arcs back down.",
          checkpoint: "Clicking launches a dot that rises, slows, and falls.",
          recovery: ["Doesn't move — the move loop must be inside tick.", "Flies off instantly — vy starts at -15 and gravity adds a small 0.3."] },
        { title: "Give it a trail", adding: "the streak behind the rocket — record points in the move loop, then draw a line in the draw loop.",
          code: `        fw["trail"].append((fw["x"], fw["y"]))\n        if len(fw["trail"]) > 15:\n            fw["trail"].pop(0)\n\n        if len(fw["trail"]) > 1:\n            canvas.create_line(fw["trail"], fill="white", width=2, tags="firework")`,
          does: "In the move loop we remember the rocket's spot (keeping the last 15). In the draw loop we connect those points into a streak. The first two lines go in the move loop; the last two in the draw loop.",
          why: "The trail turns a dot into a rocket — and it's the same grow-and-trim list idea again.",
          see: "Click — a rocket streaks up trailing a white tail behind it. That's Beat 4 — launch a rocket.",
          checkpoint: "Rockets rise with a white trailing streak.",
          recovery: ["No trail — the append goes in the move loop, the create_line in the draw loop.", "Tail too long or short — change the 15."] }
      ]
    },
    {
      id: 5, title: "The big bang",
      build: "the rocket reaches the top and bursts into a sphere of colored sparks.",
      beat: "🎆 A rocket bursts into a sphere of colored sparks.",
      steps: [
        { title: "Build the explosion machine", adding: "math, a palette, a sparks list, and a burst function (import math at top; the rest above def tick()).",
          code: `import math\n\ncolors = ["#ff3232", "#3264ff", "#32ff64", "#ffd700", "#c832ff", "#ffffff", "#ffa500"]\nsparks = []\n\ndef burst(x, y, color):\n    for i in range(60):\n        angle = random.uniform(0, 6.28)\n        speed = random.uniform(2, 6)\n        sparks.append({"x": x, "y": y, "vx": math.cos(angle) * speed, "vy": math.sin(angle) * speed, "color": color})`,
          does: "burst makes one explosion: 60 sparks from (x, y), each in a random direction (angle around a full circle) at a random speed. cos and sin turn direction + speed into sideways and vertical motion. Each spark remembers its color.",
          why: "The for-loop-makes-many idea again — 60 sparks from one call. cos/sin just point each spark a different way around a circle.",
          see: "Nothing new — the machine's built but not fired. No error.",
          checkpoint: "It runs with no error.",
          recovery: ["name 'math' is not defined — make sure import math is at the top."] },
        { title: "Fire it at the top", adding: "burst the rocket at its peak, and draw the sparks (peak-check after the move loop; spark-draw after the rocket-draw).",
          code: `    for fw in fireworks[:]:\n        if fw["vy"] >= 0:\n            burst(fw["x"], fw["y"], random.choice(colors))\n            fireworks.remove(fw)\n\n    for s in sparks:\n        canvas.create_oval(s["x"] - 2, s["y"] - 2, s["x"] + 2, s["y"] + 2, fill=s["color"], outline="", tags="firework")`,
          does: "We walk a copy of the rockets; any that's reached the top (vy >= 0 means it stopped rising) bursts in a random color and is removed. Then we draw each spark as a colored dot.",
          why: "This is the instant the rocket becomes the explosion — and it's why we tracked vy: the moment it stops rising is the top of the arc.",
          see: "Click — the rocket rises and at the top pops into a tight clump of colored sparks (frozen, for now).",
          checkpoint: "Rockets reach the top and turn into a clump of colored dots.",
          recovery: ["Rocket vanishes, no sparks — check the sparks are drawn and burst is called.", "Clump in the wrong spot — burst should use fw['x'], fw['y']."] },
        { title: "Blow it apart", adding: "motion for the sparks (add inside tick, right after the burst loop).",
          code: `    for s in sparks:\n        s["x"] += s["vx"]\n        s["y"] += s["vy"]`,
          does: "Each frame each spark moves by its velocity — and since burst aimed them every which way, they fly outward in an expanding sphere.",
          why: "Same position += velocity as the rocket, but 60 at once, each a different direction, reads as an explosion.",
          see: "🎆 Click — the rocket rises and BURSTS into a sphere of colored sparks flying outward. That's Beat 5 — the big bang.",
          checkpoint: "Explosions spray sparks outward in a colored sphere.",
          recovery: ["Sparks don't move — the loop must be inside tick.", "They fly in a line, not a ball — burst must use cos for vx and sin for vy."] }
      ]
    },
    {
      id: 6, title: "Gravity & fade",
      build: "sparks that arc, fall, slow, shrink, and die away — like the real thing.",
      beat: "Sparks fall, fade, and die away like real sparks.",
      steps: [
        { title: "Make them fall", adding: "gravity and a little drag on each spark (add inside the spark move loop, above s[\"x\"] += ...).",
          code: `        s["vy"] += 0.1\n        s["vx"] *= 0.99\n        s["vy"] *= 0.99`,
          does: "Gravity adds a little downward speed each frame; drag (× 0.99) gently slows both speeds so the sparks arc and settle instead of flying off.",
          why: "Same gravity idea as the rocket; the drag is what makes an explosion puff and settle.",
          see: "The sparks now arc outward and fall, slowing as they go. Much more like a firework.",
          checkpoint: "Sparks curve downward and slow down instead of flying straight.",
          recovery: ["Still fly straight — the three lines must be inside the spark loop."] },
        { title: "Give them a lifespan", adding: "a life counter and removing dead sparks (add \"life\" to the spark in burst; s[\"life\"] -= 1 at the end of the move loop; then a remove loop after it).",
          code: `        sparks.append({"x": x, "y": y, "vx": math.cos(angle) * speed, "vy": math.sin(angle) * speed, "color": color, "life": random.randint(60, 110)})\n\n        s["life"] -= 1\n\n    for s in sparks[:]:\n        if s["life"] <= 0:\n            sparks.remove(s)`,
          does: "Each spark is born with a random life (60–110). Every frame we count it down, and any spark that hits zero is removed (looping over a copy, so it's safe). The append line replaces the one in burst; the decrement goes at the end of the move loop; the remove loop comes right after it.",
          why: "Without this, sparks pile up forever and the program chokes. A lifespan is how anything temporary cleans up after itself.",
          see: "Sparks now disappear a second or so after the burst; the sky clears itself between fireworks.",
          checkpoint: "Sparks vanish a moment after exploding; the screen doesn't fill up.",
          recovery: ["KeyError 'life' — make sure burst's spark includes \"life\".", "They never disappear — the remove loop must be a separate loop after the move loop."] },
        { title: "Fade as they die", adding: "shrink each spark as its life runs out (change the spark-drawing line to use a size from life).",
          code: `    for s in sparks:\n        size = 1 + s["life"] // 40\n        canvas.create_oval(s["x"] - size, s["y"] - size, s["x"] + size, s["y"] + size, fill=s["color"], outline="", tags="firework")`,
          does: "Instead of every spark being the same size, we set size from its remaining life — fat when young, tiny just before it dies.",
          why: "Tkinter can't truly fade colors, but a shrinking dot reads as a spark burning out.",
          see: "🎆 Sparks now shrink as they fall and fade away. That's Beat 6 — a complete, lifelike firework.",
          checkpoint: "Sparks shrink smaller as they age, then disappear.",
          recovery: ["All the same size — replace the 2s with size, computed just above."] }
      ]
    },
    {
      id: 7, title: "Six fireworks",
      build: "six visibly different explosions, chosen with the number keys 1–6.",
      beat: "Keys 1–6 — six visibly distinct fireworks.",
      steps: [
        { title: "Choose a shape with the keys", adding: "a remembered shape and the number keys. Also: add \"shape\": current[\"shape\"] to launch's rocket, change burst to def burst(x, y, color, shape), and pass fw[\"shape\"] in the burst call.",
          code: `shapes = ["rocket", "peony", "willow", "palm", "ring", "cracker"]\ncurrent = {"shape": "rocket"}\n\ndef set_shape(name):\n    current["shape"] = name\n\nwindow.bind("1", lambda e: set_shape("rocket"))\nwindow.bind("2", lambda e: set_shape("peony"))\nwindow.bind("3", lambda e: set_shape("willow"))\nwindow.bind("4", lambda e: set_shape("palm"))\nwindow.bind("5", lambda e: set_shape("ring"))\nwindow.bind("6", lambda e: set_shape("cracker"))`,
          does: "current remembers your pick; each number key runs set_shape to change it. When you launch, the rocket remembers its shape and passes it to burst.",
          why: "Keyboard control, and the remember-a-choice pattern you'll reuse for the auto-show.",
          see: "Press 1–6, then click — they all still look the same for now, but the keys work and the choice travels through.",
          checkpoint: "It runs; clicking still makes fireworks; no error pressing 1–6.",
          recovery: ["Error about shape — burst must be def burst(x, y, color, shape): and the call must pass fw['shape']."] },
        { title: "Give each shape its own look", adding: "the recipe that makes each shape different (replace the inside of your burst function).",
          code: `def burst(x, y, color, shape):\n    count = 60\n    if shape == "peony":\n        count = 100\n    if shape == "cracker":\n        count = 90\n    for i in range(count):\n        angle = random.uniform(0, 6.28)\n        speed = random.uniform(2, 6)\n        life = random.randint(60, 110)\n        if shape == "ring":\n            angle = (i / count) * 6.28\n            speed = 5\n        elif shape == "willow":\n            speed = random.uniform(1.5, 3.5)\n            life = random.randint(110, 150)\n        elif shape == "palm":\n            angle = (i % 5) / 5 * 6.28 + random.uniform(-0.2, 0.2)\n            speed = random.uniform(5, 8)\n        elif shape == "cracker":\n            speed = random.uniform(1, 4)\n            life = random.randint(25, 50)\n        sparks.append({"x": x, "y": y, "vx": math.cos(angle) * speed, "vy": math.sin(angle) * speed, "color": color, "life": life})`,
          does: "Same loop, but each shape tweaks the sparks: peony = a bigger, denser sphere; willow = slow and long-lived (it droops); palm = five thick branches; ring = an even expanding circle; cracker = lots of tiny, fast, short-lived sparks.",
          why: "The big lesson: one function, six results, just by changing a few numbers — no copy-pasting six near-identical functions.",
          see: "🎆 Press 1–6 and click — each key now makes a clearly different explosion. That's Beat 7 — six fireworks.",
          checkpoint: "All six keys produce visibly distinct bursts (ring looks like a ring, palm has branches).",
          recovery: ["Some look identical — check the if/elif names match the keys exactly (willow, not wilow!).", "Indentation error — the if/elif block lives inside the for loop."] }
      ]
    },
    {
      id: 8, title: "The show",
      build: "random launches, a hands-free auto-show, a clear key, and a live readout.",
      beat: "🎆 A hands-free show, with a live readout.",
      steps: [
        { title: "Space launches a random firework", adding: "a spacebar that fires a random shape at a random spot (add above def tick(), and a bind with the others).",
          code: `def random_firework(event=None):\n    fireworks.append({"x": random.randint(100, 1100), "y": 800, "vx": random.uniform(-1, 1), "vy": -15, "trail": [], "shape": random.choice(shapes)})\n\nwindow.bind("<space>", random_firework)`,
          does: "random_firework launches a rocket from a random x with a random shape. event=None lets it be called both by the spacebar and by us directly (next step). The bind ties it to the spacebar.",
          why: "Reusing one function from two places — a key and, soon, the timer — keeps programs small.",
          see: "Tap space — a random firework launches somewhere across the sky.",
          checkpoint: "Pressing space fires a random firework.",
          recovery: ["shapes is not defined — this builds on Chapter 7, where shapes comes from."] },
        { title: "An auto-show", adding: "press R to make fireworks fire on their own (update current to add auto/timer; add toggle_auto + bind; add the timer block inside tick, after the star loop).",
          code: `current = {"shape": "rocket", "auto": False, "timer": 0}\n\ndef toggle_auto(event=None):\n    current["auto"] = not current["auto"]\n\nwindow.bind("r", toggle_auto)\n\n    if current["auto"]:\n        current["timer"] += 1\n        if current["timer"] >= 90:\n            current["timer"] = 0\n            random_firework()`,
          does: "R flips auto on or off. While it's on, the loop counts frames in timer; every 90 frames (about 1.5s) it resets and fires a random firework. (The first lines replace your current line and go above tick; the if-block goes inside tick.)",
          why: "This is your first timer — 'do something every so often' — built from counting frames in the loop you already have.",
          see: "Press R — fireworks start launching on their own, about every 1.5 seconds. Press R again to stop.",
          checkpoint: "R starts and stops a hands-free firework show.",
          recovery: ["Nothing auto-fires — the if-block must be inside tick; current must have \"auto\" and \"timer\"."] },
        { title: "A clear key", adding: "press C to wipe the sky (add a function and a bind).",
          code: `def clear_all(event=None):\n    fireworks.clear()\n    sparks.clear()\n    canvas.delete("firework")\n\nwindow.bind("c", clear_all)`,
          does: "Empties both lists and erases every shape tagged \"firework\" — leaving the stars and moon untouched (they aren't tagged).",
          why: "A reset is a small kindness — and a neat reminder of why we tagged the moving things separately.",
          see: "During a busy show, press C — all rockets and sparks vanish instantly; the sky stays.",
          checkpoint: "C clears the fireworks but leaves the stars and moon.",
          recovery: ["The stars vanish too — you must delete \"firework\", not everything."] },
        { title: "A live readout", adding: "a little text panel showing the current shape and spark count (create it above def tick(); update it inside tick, above window.after).",
          code: `hud = canvas.create_text(20, 20, anchor="nw", fill="#88ff88", font=("Arial", 12), text="")\n\n    canvas.itemconfig(hud, text=f"Shape: {current['shape']}    Sparks: {len(sparks)}")\n    canvas.tag_raise(hud)`,
          does: "create_text makes one text item top-left. Each frame we update its words with the current shape and how many sparks are alive, and tag_raise lifts it above the fireworks so it's always readable.",
          why: "A readout turns a toy into something that feels finished — and it's just itemconfig again, the same tool that twinkles the stars.",
          see: "🎆 A soft green readout in the corner, updating live as you switch shapes and sparks come and go. That's Beat 8 — the show.",
          checkpoint: "The readout shows the current shape and a live spark count, sitting on top of everything.",
          recovery: ["Readout hidden behind sparks — make sure canvas.tag_raise(hud) runs each frame."] }
      ]
    }
  ]
};
